name: Releaser

on:
  push:
    branches:
      - main

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Release
        if: ${{ steps.release.outputs.release_created }}
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --config=.github/goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
