name: Releaser

on:
  push:
    branches:
      - main

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          release-type: go