name: create tag

on:
  push:
    branches:
      - main
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/release-please-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: go